# Site settings
title: "Moon Jong Heon Profile"
description: "Moon Jong Heon Profile"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Moon Jong Heon"
resume_title:                   "<b>Mobile Developer</b>"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "answhdgjs@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "</p><li>10년차 안드로이드 개발자</li><li>개발을 즐기는 개발자</li><li>새롭게 알게된 지식을 공유 하며 커뮤니케이션을 좋아하는 개발자</li><li>개발에 중심이 되고 싶은 개발자</li><li>Email: <a href='mailto:answhdgjs@gmail.com'>answhdgjs@gmail.com</a></li><li>Blog: <a href='https://keyman4949.tistory.com/'>https://keyman4949.tistory.com/</a></li><li>GitHub: <a href='https://github.com/jongheonmoon'>https://github.com/jongheonmoon</a></li>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jongheonmoon"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://keyman4949.tistory.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://keyman4949.tistory.com/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
